# Generated by Django 4.2.8 on 2023-12-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followimage',
            name='image',
            field=models.ImageField(upload_to='follow_images'),
        ),
    ]
