# Generated by Django 4.2.8 on 2023-12-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_followimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followimage',
            old_name='image',
            new_name='image_data',
        ),
    ]
