# Generated by Django 4.2.8 on 2023-12-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_image_followimage_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followimage',
            name='image_data',
        ),
        migrations.AddField(
            model_name='followimage',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
