# Generated by Django 4.2.4 on 2023-09-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='color',
            name='color_id',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='FFFFFF', max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='store.category'),
        ),
    ]
