# Generated by Django 4.1.13 on 2023-12-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_followimage_image_data_followimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followimage',
            name='image_file',
        ),
        migrations.AlterField(
            model_name='followimage',
            name='image',
            field=models.ImageField(upload_to='follow_images'),
        ),
    ]
