# Generated by Django 4.2.4 on 2023-09-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_category_color_color_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='multiple_colors',
            field=models.BooleanField(default=False),
        ),
    ]
