# Generated by Django 4.2.4 on 2023-09-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
