# Generated by Django 4.2.4 on 2023-09-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_color_name_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
