# Generated by Django 4.2.4 on 2023-09-27 19:50

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_color_name_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=store.models.product_image_upload_path),
        ),
    ]
