# Generated by Django 4.2.4 on 2023-09-28 11:10

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_image_id', models.CharField(blank=True, max_length=1, unique=True)),
                ('image', models.ImageField(upload_to=store.models.follow_image_upload_path)),
            ],
        ),
    ]
