# Generated by Django 4.2.4 on 2023-10-14 17:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_active_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(upload_to=accounts.models.profile_image_upload_path),
        ),
    ]
